### PR TITLE
Revert to R6 for streaming

### PR DESCRIPTION
**Pull request by calderonsamuel**
Right now this is just a placeholder for the job. I wasn't able to find the time before (because of the LatinR conference), but I'll have some free time this and next week that should allow me to get this done. Sorry for the delay!

### CODE REVIEW

**Comment by calderonsamuel** [comment]
Good news @JamesHWade 

At this point he have a working `StreamHandler` inside `gptstudio_request_perform()`. We are no longer writing and reading streams from disk! 🥳 

So far I have encountered two problems:

1. We always need to click the settings button to not get them as NULL. I believe this is because it is rendered as a ModalDialog. 
2. The user message gets recorded twice in the chat history. This of course renders it twice each time in the chat windows. (should be easy to fix)
3. The stream is still inconsistent, and sometimes breaks in the middle of a response. Once 1 and 2 are  fixed it should be enough to merged this PR and ask users to try to break it.

I also think there are some things to improve in the skeleton building process, but that will become a separate issue

**Comment by calderonsamuel** [comment]
All ready to merge

fix #143 , fix #148

**Comment by JamesHWade** [comment]
Sorry for the delay, @calderonsamuel. My wife gave birth to twins last month, so I have been a bit preoccupied. Thank you for this fantastic contribution, as usual.

**Comment by calderonsamuel** [comment]
> Sorry for the delay, @calderonsamuel. My wife gave birth to twins last month, so I have been a bit preoccupied. Thank you for this fantastic contribution, as usual.

Don't worry. Congratulations to you both!

**Pull request merged**
