### PR TITLE
Clean `check()` and readme edits

### PR DESCRIPTION
**Pull request by JamesHWade**
I really like the idea and would love to contribute to it! Great work! I haven't played with RStudio add-ins before, so I'm excited to learn and hopefully help!

Aside from cleaning up code and readme, I made a few "opinionated" changes I don't want you to miss.

1. I change the name from  `GPTstudio` to `gptstudio`. My style is to keep package names to all lowercase.
2. I added the MIT license. I hope that's okay. If not, it would be good to at least pick some license rather than leaving it unspecified.

Again, really great work! I'm excited for this to mature and expand!

### CODE REVIEW

**Comment by MichelNivard** [comment]
I’ll study whether I don’t inherit a licensing obligation from another dependency for a bit tonight and then make a choice. Can you explain why it’s beneficial to have lower case package names? Is it habit, convention or a substantive choice I can’t oversee the consequences for?

**Comment by JamesHWade** [comment]
For the license, you should have control over any code that you write assuming you are not directly reusing code from elsewhere. All dependencies - openai, miniUI, shiny, and rstudioapi - use either MIT or GPL-3.

The package name is not a big deal, but I recommend sticking with all lowercase since it can be hard for others to remember the name (e.g., GPTStudio vs GPTstudio).

**Comment by MichelNivard** [comment]
Okay sounds reasonable I’ll accept when I get to a computer

**Comment by MichelNivard** [comment]
I’ll add you as contributor if you want?

**Comment by MichelNivard** [comment]
@JamesHWade: I , an academic cosplaying as a coder, edit packages manually, or from the GitHub website (I know, I know...), you, clearly more organized, do not. So I may end up clearing out some of the .Rmd files and .Rproj files I don't know what to do with at some point.

**Pull request merged**
